# Generated by Django 3.0.5 on 2020-05-05 21:03

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_block', wagtail.core.fields.StreamField([('footer_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, max_length=24, null=True))], help_text='title and text', required=False))], blank=True, null=True)),
            ],
        ),
    ]
