# Generated by Django 3.0.5 on 2020-05-05 21:03

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('webbase', '0001_initial'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('hero_name', models.CharField(help_text='Place name. Shown if no logo image.', max_length=255)),
                ('facets', wagtail.core.fields.StreamField([('facet', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=24)), ('subtitle', wagtail.core.blocks.CharBlock(max_length=32)), ('paragraph', wagtail.core.blocks.TextBlock(max_length=255)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))], help_text='E.g. Restuarant, Hotel, Function Hall', max_length=650, required=False))])),
                ('body', wagtail.core.fields.StreamField([])),
                ('footer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='webbase.Footer')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Large image on the home page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('hero_logo', models.ForeignKey(blank=True, help_text='Place logo. If none, defaults to place name.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'homepage',
            },
            bases=('wagtailcore.page',),
        ),
    ]
