# Generated by Django 3.0.5 on 2020-05-05 22:11

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='facets',
            field=wagtail.core.fields.StreamField([('facet', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=24)), ('subtitle', wagtail.core.blocks.CharBlock(max_length=32)), ('paragraph', wagtail.core.blocks.TextBlock(max_length=255)), ('page', wagtail.core.blocks.PageChooserBlock())], help_text='E.g. Restuarant, Hotel, Function Hall', max_length=650, required=False))]),
        ),
    ]
