# Generated by Django 3.0.5 on 2020-05-01 14:29

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('webbase', '0001_initial'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'homepage'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('facet', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=24)), ('subtitle', wagtail.core.blocks.CharBlock(max_length=32)), ('paragraph', wagtail.core.blocks.TextBlock(max_length=255)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))], help_text='the adding text', max_length=650, required=False))], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='webbase.Footer'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Large image on the home page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_logo',
            field=models.ForeignKey(blank=True, help_text='Place logo. If none, defaults to place name.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_name',
            field=models.CharField(default='', help_text='Place name. Shown if no logo image.', max_length=255),
            preserve_default=False,
        ),
    ]
